title: Chonglei Zhan's Homepage
page-top-title: Chonglei Zhan
#top-section-bg-text: Be what you wanna be
home-subtitle: Name&ensp;|&ensp;詹崇磊
copyright-text: '&copy; Chonglei Zhan 2023-2025. All Rights Reserved.'
